### ISSUE TITLE
Concatenate regular *.css files into style-bundles

### ISSUE THREAD

**Issue by h3nn3s** [arminlinzbauer/gulpex#21]
It would be a great enhancement if one could concatenate regular css files to style bundles.

Use case:
Use a third-party lib. (e.g. fancybox, without scss sources) and compile it into the same css file as all other scss sources.

Current behavior:
For every regular css-file putted to the bundle array a new css file is generated.

**Comment by h3nn3s** [comment]
![index](https://user-images.githubusercontent.com/342046/91891242-f6e6fb80-ec90-11ea-8894-2720f7250106.jpeg)

**Comment by arminlinzbauer** [comment]
> For every regular css-file putted to the bundle array a new css file is generated.

All specified files are piped through the SCSS compiler. Per design, the compiler creates a new file for every input file that doesn't start with `_`. 

Sadly, @importing plain CSS files from SCSS was discontinued a while back, so concatenating isn't only the "better" option, but the only feasible option.

**Comment by arminlinzbauer** [comment]
A change like this would mean the following:

 - `files`-node must be pre-processed with a glob matching library because a glob pattern could, in theory, match any combination of CSS, Sass and SCSS files
 - `files`-node's order must be preserved throughout this process
 - all matched files must then be concatenated, in order, into a bundle file while simultaneously recognizing Sass and SCSS files and piping those through the Sass compiler before concatenating them to the bundle. Again, file order must be preserved throughout the process because later files might overwrite CSS instructions of earlier files.

This seems like a lot of work for little benefit. But please do submit your ideas on how to tackle this problem. Maybe we can find a simpler way of achieving a similar or identical result?

**Comment by h3nn3s** [comment]
Thanks for your detailed informations on this issue.

After reading your comments, I think we should close this issue for the moment.
To much work for to less benefits, additionally the suggested steps sound like a performance-hell when "watching" for changes.

This issue can be worked around with css concatenation of your desired CMS.
